[project]
name = "pythonFapiao"
version = "0.1.0"
description = "发票合并工具"
readme = "README.md"
requires-python = ">=3"
dependencies = [
    "dotenv>=0.9.9",
    "pypdf>=1.13",
    "tencentcloud-sdk-python>=3.0.1475",
]
